/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELSONIC_H__
#define __3D_MODELSONIC_H__

static POINT PointSonic[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic[] =
    {
        {{742, -55390, 35018}, {4, 14, 15, 15}},
        {{-4130, -65405, -2}, {15, 13, 4, 4}},
        {{24233, -58120, 18158}, {16, 17, 18, 18}},
        {{24232, -58120, 18158}, {19, 20, 21, 21}},
        {{38886, -33575, 40688}, {4, 12, 22, 22}},
        {{743, -55391, 35016}, {22, 14, 4, 4}},
        {{24198, -58172, -18036}, {23, 24, 25, 25}},
        {{-4130, -65405, -2}, {26, 25, 27, 27}},
        {{756, -55403, -34997}, {28, 29, 27, 27}},
        {{757, -55402, -34998}, {28, 30, 31, 31}},
        {{38884, -33567, -40695}, {31, 32, 28, 28}},
        {{24199, -58172, -18037}, {18, 32, 33, 33}},
        {{24234, -58120, 18157}, {18, 29, 28, 28}},
        {{32021, -57180, -24}, {16, 34, 35, 35}},
        {{64546, -11344, 12}, {36, 23, 37, 37}},
        {{64546, -11344, 13}, {21, 35, 38, 38}},
        {{32022, -57179, -23}, {39, 19, 37, 37}},
        {{24199, -58172, -18038}, {37, 40, 36, 36}},
        {{64546, -11343, 16}, {38, 40, 21, 21}},
        {{38887, -33572, 40688}, {19, 39, 20, 20}},
        {{24234, -58120, 18158}, {27, 25, 41, 41}},
        {{24199, -58172, -18038}, {41, 30, 27, 27}},
        {{38885, -33567, -40695}, {17, 20, 18, 18}},
        {{64546, -11344, 14}, {27, 39, 26, 26}},
        {{-4129, -65405, -4}, {18, 33, 16, 16}},
        {{-21386, -61947, -257}, {42, 43, 44, 44}},
        {{-3207, -55733, -34328}, {27, 30, 28, 28}},
        {{-3208, -55733, -34327}, {28, 32, 18, 18}},
        {{756, -55402, -34999}, {22, 12, 24, 24}},
        {{-4129, -65405, -2}, {34, 13, 15, 15}},
        {{10226, 8905, -64117}, {15, 35, 34, 34}},
        {{-60149, -1658, -25966}, {24, 23, 22, 22}},
};

static ATTR AttributeSonic[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic =
    {
        .data =
            {
                PointSonic,
                52,
                PolygonSonic,
                32,
                AttributeSonic}};

static POINT PointSonic2[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic2[] =
    {
        {{32023, -57179, -23}, {2, 3, 4, 4}},
        {{24234, -58120, 18157}, {4, 5, 2, 2}},
        {{-4130, -65405, -4}, {7, 9, 6, 6}},
        {{-4132, -65405, -4}, {10, 9, 8, 8}},
        {{24200, -58171, -18037}, {12, 4, 3, 3}},
        {{32022, -57179, -25}, {3, 7, 12, 12}},
        {{36974, -42653, 33294}, {5, 4, 13, 13}},
        {{60787, -17652, 16976}, {13, 10, 5, 5}},
        {{40257, -18618, 48245}, {3, 2, 8, 8}},
        {{8439, 4647, -64823}, {8, 2, 5, 5}},
        {{62006, 21217, -212}, {8, 7, 3, 3}},
        {{65330, -1816, -4855}, {5, 10, 8, 8}},
        {{-52063, -26274, -29899}, {7, 8, 9, 9}},
        {{-57318, -31766, -634}, {10, 11, 9, 9}},
};

static ATTR AttributeSonic2[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic2 =
    {
        .data =
            {
                PointSonic2,
                52,
                PolygonSonic2,
                14,
                AttributeSonic2}};

static POINT PointSonic3[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic3[] =
    {
        {{-18752, 50908, -36764}, {17, 16, 35, 35}},
        {{-61142, -23591, 0}, {15, 38, 35, 35}},
        {{-62890, 13078, -12988}, {23, 36, 22, 22}},
        {{-63717, -10866, -10815}, {26, 39, 37, 37}},
        {{-4130, -65405, -3}, {26, 23, 25, 25}},
        {{741, -55390, 35018}, {20, 17, 21, 21}},
        {{-3613, -55737, 34281}, {19, 21, 40, 40}},
        {{-3613, -55737, 34281}, {19, 40, 37, 37}},
        {{-21386, -61947, -257}, {36, 40, 14, 14}},
        {{-4129, -65405, -4}, {40, 38, 14, 14}},
        {{-13909, -22383, 60003}, {29, 18, 20, 20}},
        {{3751, -21719, 61718}, {27, 29, 39, 39}},
};

static ATTR AttributeSonic3[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic3 =
    {
        .data =
            {
                PointSonic3,
                52,
                PolygonSonic3,
                12,
                AttributeSonic3}};

static POINT PointSonic4[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic4[] =
    {
        {{10220, 8867, 64123}, {30, 41, 25, 25}},
        {{-60150, -1660, 25964}, {32, 16, 33, 33}},
};

static ATTR AttributeSonic4[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc1f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc1f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic4 =
    {
        .data =
            {
                PointSonic4,
                52,
                PolygonSonic4,
                2,
                AttributeSonic4}};

static POINT PointSonic5[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic5[] =
    {
        {{10222, 8867, 64123}, {24, 6, 45, 45}},
        {{-18781, 50843, 36840}, {46, 11, 34, 34}},
        {{11581, 64504, 92}, {34, 16, 46, 46}},
        {{-60348, 25552, -159}, {45, 25, 24, 24}},
};

static ATTR AttributeSonic5[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic5 =
    {
        .data =
            {
                PointSonic5,
                52,
                PolygonSonic5,
                4,
                AttributeSonic5}};

static POINT PointSonic6[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic6[] =
    {
        {{-18782, 50842, 36841}, {30, 25, 45, 45}},
        {{11580, 64504, 92}, {16, 32, 46, 46}},
};

static ATTR AttributeSonic6[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic6 =
    {
        .data =
            {
                PointSonic6,
                52,
                PolygonSonic6,
                2,
                AttributeSonic6}};

static POINT PointSonic7[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic7[] =
    {
        {{39288, 48480, 20024}, {45, 6, 9, 9}},
        {{42233, 50112, -1}, {9, 11, 46, 46}},
        {{42233, 50113, 0}, {9, 47, 45, 45}},
        {{39289, 48506, -19960}, {46, 47, 9, 9}},
};

static ATTR AttributeSonic7[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic7 =
    {
        .data =
            {
                PointSonic7,
                52,
                PolygonSonic7,
                4,
                AttributeSonic7}};

static POINT PointSonic8[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic8[] =
    {
        {{11581, 64504, 93}, {30, 45, 47, 47}},
        {{-18754, 50907, -36765}, {32, 31, 47, 47}},
        {{39292, 48505, -19958}, {47, 31, 30, 30}},
        {{8404, 51829, -39217}, {47, 46, 32, 32}},
};

static ATTR AttributeSonic8[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc1f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc1f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc1f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc1f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic8 =
    {
        .data =
            {
                PointSonic8,
                52,
                PolygonSonic8,
                4,
                AttributeSonic8}};

static POINT PointSonic9[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic9[] =
    {
        {{-18752, 50907, -36765}, {21, 17, 35, 35}},
        {{-60349, 25550, -165}, {26, 37, 23, 23}},
        {{11580, 64504, 92}, {36, 14, 22, 22}},
        {{10227, 8906, -64117}, {15, 14, 38, 38}},
        {{3751, -21719, -61718}, {20, 39, 29, 29}},
};

static ATTR AttributeSonic9[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic9 =
    {
        .data =
            {
                PointSonic9,
                52,
                PolygonSonic9,
                5,
                AttributeSonic9}};

static POINT PointSonic10[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic10[] =
    {
        {{-13000, -22001, -60347}, {48, 49, 50, 50}},
        {{-52998, -26715, 27792}, {49, 51, 50, 50}},
        {{-13909, -22384, 60003}, {51, 48, 50, 50}},
        {{-63749, -10685, 10805}, {42, 49, 48, 48}},
        {{-63717, -10867, -10815}, {48, 43, 42, 42}},
        {{-13003, -22000, -60347}, {44, 51, 49, 49}},
        {{-52061, -26277, -29901}, {49, 42, 44, 44}},
        {{-62875, 13190, 12949}, {48, 51, 44, 44}},
        {{-61141, -23592, -2}, {44, 43, 48, 48}},
};

static ATTR AttributeSonic10[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x8200, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic10 =
    {
        .data =
            {
                PointSonic10,
                52,
                PolygonSonic10,
                9,
                AttributeSonic10}};

static POINT PointSonic11[] =
    {
        {114695, 1785271, 0},
        {352086, 1787511, 0},
        {816948, 1777273, 0},
        {722568, 1772794, 288899},
        {234990, 1671055, 0},
        {722568, 1772794, -287299},
        {731206, 1945558, 466142},
        {776317, 1863335, 406314},
        {967637, 1945558, 0},
        {924446, 2024901, 0},
        {776637, 1863655, -406954},
        {731206, 1945558, -466142},
        {234990, 1773754, 414953},
        {234990, 1773754, -414953},
        {-172283, 1803507, 0},
        {-52948, 1803507, -400235},
        {234990, 2556310, -659061},
        {-1118005, 2449772, -862859},
        {66386, 2924551, -407274},
        {-1100729, 2022661, 0},
        {-329051, 2620617, -227472},
        {-317533, 2268690, -316733},
        {-52948, 1803507, 400236},
        {-230831, 2149995, 578758},
        {234990, 2045377, 659062},
        {234990, 2556310, 659062},
        {-1118005, 2449772, 862859},
        {66386, 2924551, 407274},
        {-92940, 3225609, 1599},
        {-1152238, 3276800, -3199},
        {522930, 2924551, 287939},
        {642265, 2877842, 0},
        {522930, 2924551, -287939},
        {378960, 3212172, -738405},
        {234990, 2045377, -659061},
        {-230831, 2149995, -578758},
        {-826227, 1692491, 628348},
        {-317533, 2268690, 316733},
        {-826227, 1692491, -663540},
        {-329051, 2620617, 227792},
        {-326171, 2025221, 0},
        {378960, 3207692, 740005},
        {942682, 1991308, 7678},
        {942682, 1991308, -8318},
        {961558, 1956755, -320},
        {731206, 2554389, 465822},
        {731206, 2554389, -465822},
        {924126, 2476326, 0},
        {1018506, 2114483, -63986},
        {1018506, 2114483, 61747},
        {1124084, 2163432, -1599},
        {1152238, 2045377, -1599},
};

static POLYGON PolygonSonic11[] =
    {
        {{-63749, -10686, 10806}, {12, 7, 6, 6}},
        {{-63749, -10687, 10804}, {13, 34, 11, 11}},
        {{-57319, -31764, -631}, {6, 24, 12, 12}},
        {{-52995, -26717, 27795}, {11, 10, 13, 13}},
};

static ATTR AttributeSonic11[] =
    {
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
        ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0xfc00, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh MeshSonic11 =
    {
        .data =
            {
                PointSonic11,
                52,
                PolygonSonic11,
                4,
                AttributeSonic11}};

/* Call this function in you code to display all objects */
static __jo_force_inline void display_sonic_mesh(void)
{
    jo_3d_mesh_draw(&MeshSonic);
    /* Add matrix transformation here like jo_3d_rotate_matrix() */
    jo_3d_mesh_draw(&MeshSonic2);
    jo_3d_mesh_draw(&MeshSonic3);
    jo_3d_mesh_draw(&MeshSonic4);
    jo_3d_mesh_draw(&MeshSonic5);
    jo_3d_mesh_draw(&MeshSonic6);
    jo_3d_mesh_draw(&MeshSonic7);
    jo_3d_mesh_draw(&MeshSonic8);
    jo_3d_mesh_draw(&MeshSonic9);
    jo_3d_mesh_draw(&MeshSonic10);
    jo_3d_mesh_draw(&MeshSonic11);
}

#endif /* !__3D_MODELSONIC_H__ */
